name: ci
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # Run the local version of the action.
        with:
          version: '1.30.1'
          github_token: ${{ github.token }}
      - run: api-linter --version
